---
# This playbook installs and configures zabbix proxy on centos 8
# According to instructions at https://www.zabbix.com/documentation/4.0/manual/installation/install_from_packages/rhel_centos
- name: Install and configure Zabbix proxy
  hosts: zabbix
  vars:
    zabbix_password: zabbix
    zabbix_server: minizabbix.sf.loc
  tasks:
    - name: Install Zabbix repository
      yum:
        name: https://repo.zabbix.com/zabbix/4.0/rhel/8/x86_64/zabbix-release-4.0-2.el8.noarch.rpm
        state: present
        #validate_certs: no

    - name: Update yum cache
      yum:
        update_cache: yes

    - name: Install packages
      yum:
        name:
          - zabbix-proxy-mysql
          - zabbix-web-mysql
          - zabbix-agent
          - python3-PyMySQL
          - mysql-server

    - name: Start MySQL service
      service:
          name: mysqld
          enabled: yes
          state: started

    - name: Create Zabbix database
      mysql_db:
          name: zabbix 
          encoding: utf8
          # login_user: root
          # login_host: localhost
          # login_password: ""
          collation: utf8_bin
          state: present
    
    - name: Create MySQL user
      mysql_user:
          name: zabbix
          password: "{{ zabbix_password }}"
          state: present
          host: localhost
          priv: 'zabbix.*:ALL'

    - name: Check if it's neccesary to uncompress dump file
      stat:
          path: /usr/share/doc/zabbix-proxy-mysql/schema.sql
      register: dump_file

    - name: Extract sql dump with initial schema
      command: "gzip -d /usr/share/doc/zabbix-proxy-mysql/schema.sql.gz"
      when: dump file is defined and not dump_file.stat.exists

    - name: Check if database already exists
      mysql_db:
        name: zabbix
        state: present
      register: zabbix_db_exists
          
    - name: Import initial schema
      mysql_db:
        state: import
        name: zabbix
        target: /usr/share/doc/zabbix-proxy-mysql/schema.sql
      when: zabbix_db_exists.changed

    - name: Configure database for Zabbix server/proxy (DBHost=localhost)
      lineinfile:
        path: /etc/zabbix/zabbix_proxy.conf
        regexp: '^DBHost='
        line: DBHost=localhost

    - name: Configure database for Zabbix server/proxy (DBName=zabbix)
      lineinfile:
        path: /etc/zabbix/zabbix_proxy.conf
        regexp: '^DBName='
        line: DBName=zabbix

    - name: Configure database for Zabbix server/proxy (DBUser=zabbix)
      lineinfile:
        path: /etc/zabbix/zabbix_proxy.conf
        regexp: '^DBUser='
        line: DBUser=zabbix
        
    - name: "Configure database for Zabbix server/proxy (DBPassword={{ zabbix_password }})"
      lineinfile:
        path: /etc/zabbix/zabbix_proxy.conf
        regexp: '^DBUser='
        line: "DBUser={{ zabbix_password }}"

    - name: Make zabbix SE policy package active
      command: "semodule -i zabbix_server.limits.pp"

    - name: Start zabbix-proxy service
      service:
          name: zabbix-proxy
          enabled: yes
          state: started

    # - name: Configure Zabbix agent Server
    #   lineinfile:
    #     path: /etc/zabbix/zabbix_agent.conf
    #     regexp: '^Server='
    #     line: "Server={{ zabbix_server }}"

    # - name: Configure Zabbix agent ServerActive
    #   lineinfile:
    #     path: /etc/zabbix/zabbix_agent.conf
    #     regexp: '^ServerActive='
    #     line: "ServerActive={{ zabbix_server }}"
    

    


    

    

      